# Generated by Django 4.1.13 on 2024-03-04 15:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_Name', models.CharField(max_length=32)),
                ('last_Name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ParoleOfficer',
            fields=[
                ('parole_officer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_Name', models.CharField(max_length=32)),
                ('last_Name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ReturningCitizen',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_Name', models.CharField(max_length=32)),
                ('last_Name', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('date_activated', models.DateField()),
                ('date_deactivated', models.DateField(blank=True, null=True)),
                ('daily_action_steps', models.JSONField(default=list)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('_Mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor', to='database.mentor')),
                ('_ParoleOfficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parole_officer', to='database.paroleofficer')),
            ],
        ),
        migrations.AddField(
            model_name='paroleofficer',
            name='returning_citizens',
            field=models.ManyToManyField(blank=True, editable=False, to='database.returningcitizen'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='returning_citizens',
            field=models.ManyToManyField(blank=True, editable=False, related_name='users', to='database.returningcitizen'),
        ),
    ]
