# Generated by Django 4.1.13 on 2024-03-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returningcitizen',
            old_name='daily_action_steps',
            new_name='daily_actions',
        ),
    ]
