# Generated by Django 4.1.13 on 2024-03-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_returningcitizen_mdoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returningcitizen',
            old_name='mDOC',
            new_name='MDOC',
        ),
        migrations.RemoveField(
            model_name='returningcitizen',
            name='daily_actions',
        ),
        migrations.CreateModel(
            name='DailyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('returning_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_actions', to='database.returningcitizen')),
            ],
        ),
    ]
