# Generated by Django 4.1.13 on 2024-03-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_returningcitizen_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('emoji', models.CharField(max_length=1)),
                ('rating', models.IntegerField()),
                ('returning_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_responses', to='database.returningcitizen')),
            ],
        ),
    ]
