# Generated by Django 4.1.13 on 2024-03-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_dailyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyresponse',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='dailyresponse',
            name='date',
            field=models.DateField(),
        ),
    ]
