# Generated by Django 4.1.13 on 2024-03-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_dailyresponse_emoji_alter_dailyresponse_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returningcitizen',
            old_name='_Mentor',
            new_name='myMentor',
        ),
        migrations.RenameField(
            model_name='returningcitizen',
            old_name='_ParoleOfficer',
            new_name='myParoleOfficer',
        ),
    ]
