# Generated by Django 4.1.13 on 2024-03-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename__mentor_returningcitizen_mymentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=6, unique=True)),
                ('returning_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='database.returningcitizen')),
            ],
        ),
    ]
