# Generated by Django 4.1.13 on 2024-03-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_tempuserlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuserlogin',
            name='returning_citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='database.returningcitizen'),
        ),
    ]
