# Generated by Django 4.1.13 on 2024-03-05 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_tempuserlogin_returning_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuserlogin',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
