# Generated by Django 4.1.13 on 2024-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_tempuserlogin_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuserlogin',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
