# Generated by Django 4.1.13 on 2024-03-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_tempuserlogin_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyForReturningCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=100)),
                ('returning_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiKey', to='database.returningcitizen')),
            ],
        ),
    ]
