# Generated by Django 4.1.13 on 2024-03-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_apikeyforreturningcitizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='returningcitizen',
            name='parole_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.paroleaddress'),
        ),
    ]
