# Generated by Django 4.1.13 on 2024-03-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_returningcitizen_parole_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returningcitizen',
            name='parole_address',
        ),
    ]
