# Generated by Django 4.1.13 on 2024-03-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_returningcitizen_parole_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroleaddress',
            name='returning_citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paroleAddress', to='database.returningcitizen'),
        ),
    ]
