# Generated by Django 4.1.13 on 2024-03-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_paroleaddress_returning_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paroleaddress',
            name='returning_citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paroleAddress', to='database.returningcitizen'),
        ),
    ]
