# Generated by Django 4.1.13 on 2024-03-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_paroleaddress_returning_citizen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paroleaddress',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='paroleaddress',
            name='address_2',
        ),
    ]
