# Generated by Django 4.1.13 on 2024-03-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_event_threedailyactions_delete_dailyaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedailyactions',
            name='date_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
