# Generated by Django 4.1.13 on 2024-03-11 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_threedailyactions_date_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedailyactions',
            name='date_only',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
