# Generated by Django 4.1.13 on 2024-03-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_alter_tempuserlogin_returning_citizen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikeyforparoleofficer',
            old_name='mentor',
            new_name='parole_officer',
        ),
    ]
