# Generated by Django 4.1.13 on 2024-03-28 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_rename_mentor_apikeyforparoleofficer_parole_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHealthOrganization',
            fields=[
                ('cho_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
