# Generated by Django 4.1.13 on 2024-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_communityhealthorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityhealthorganization',
            name='phone_number',
            field=models.CharField(default=55555555555, max_length=32),
            preserve_default=False,
        ),
    ]
